// Backend values — must match the Postgres category enum exactly and list should be same length
// as the list of categories in all i18n files
export const CATEGORY_KEYS = [
  "science",
  "math",
  "music",
  "art",
  "sports",
  "technology",
  "language",
  "other",
  "physics",
  "chemistry",
  "biology",
  "astronomy",
  "earth science",
  "data science",
  "robotics",
  "engineering",
  "statistics",
  "coding",
  "painting",
  "drawing",
  "sculpture",
  "photography",
  "filmmaking",
  "graphic design",
  "fashion",
  "crafts",
  "creative writing",
  "instrumental music",
  "vocal music",
  "theater",
  "acting",
  "dance",
  "improv",
  "soccer",
  "basketball",
  "tennis",
  "swimming",
  "martial arts",
  "yoga",
  "fitness",
  "running",
  "hiking",
  "cycling",
  "language learning",
  "linguistics",
  "history",
];
